### ISSUE TITLE
[ REFACTOR ] : manito-matches 테이블 추가 및 마니또 전체 코드 리팩토링

### ISSUE THREAD

**Issue by listoria** [kkb00714/ManiToOne#111]
##  설명
manito-matches 테이블 추가에 따른 마니또 기능 전체 리팩토링

## TO-DO
- [x] manito-matches Entity 작성
- [x] manito-letter의 user_id, post_id삭제 -> manito_matches_id 추가
- [x] 전체 코드 리팩토링

## 기타
기타 사항을 작성해 주세요
