### ISSUE TITLE
[ FEAT ] 프론트엔드 상세 기술 추가

### ISSUE THREAD

**Issue by kkb00714** [kkb00714/ManiToOne#115]
##  설명
로그인 페이지, 회원가입 페이지 등에서의 편의 기능을 추가합니다. 

## TO-DO
- [x] 로그인 시 헤더의 'more icon' 부분에 로그아웃 기능 추가하기
- [x] 이메일, 닉네임 자동 검사 기능 추가하기
- [x] 로딩 기능 다시 추가하기 (기능이 갑자기 사라졌던 이슈가 있음)
- [x] 비밀번호 표시 기능 추가하기

## 기타
로그아웃 기능 추가 시 툴팁이 제대로 이루어지지 않아, 팀원과 함께 논의 해봐야 함.
