### ISSUE TITLE
[ Refactor ] : 12월 16일자 수정 요청 받은것들

### ISSUE THREAD

**Issue by sqrt3** [kkb00714/ManiToOne#127]
##  설명
오늘 받은 피드백을 바탕으로 발견된 문제나 보완되어야 할 부분입니다.

## TO-DO
- [x] 프로필 수정에서도 내가 쓴 비밀번호 보이게 해주세요(이거 비밀번호 바꾸는 화면 맞죠?)
- [x] 프로필 수정에서 수정사항 반영이 안 되는 것 같아요
- [x] 프로필에서 이미 팔로우한 유저라면 해당 유저의 피드(게시글)에서 팔로우 버튼 없애는 게 나을 것 같아요
- [x] 좋아요 취소가 토글로 가능했으면 좋겠어요 + 좋아요 취소하려면 좋아요 누른 피드로 들어가서 '삭제하기'를 누름 -> 확인 메세지가 '정말로 이 게시글을 삭제하시겠습니까?'라서 수정 필요함
- [x] 좋아요하고 잠시 후 좋아요 재시도시 (다시 누르면) 카운트가 2로 올라간 것처럼 표시됨.
- [x] 숨김처리 한 게시글 다시 숨김 취소 가능하면 좋겠어요
- [x] 좋아요 누른 피드 부분에서 남의 게시글인데 자신의 닉네임이 표시돼요
- [x] 팔로우 목록에서 프로필사진이랑 글자 사이의 여백이 조금 있으면 좋겠어요.
- [x] 팔로우 목록에서 닫기 버튼 컬러를 마니또그린(#3f624c)으로 바꿔주면 좋겠어요
- [x] 마이페이지 진입시 로그인이 안 되어 있다면 로그인 페이지로 리다이렉트가 되면 좋겠어요
- 12월 17일 기준 추가사항
- [x] 프로필 페이지에서 게시글 내용 클릭 시 게시글 상세보기 페이지로 이동
- [x] 프로필 페이지에서 자신과 팔로우한 유저의 팔로우 버튼 제거
- [x] 신고하기 버튼 누를 시 게시글을 신고할 수 있도록 연결

## 기타
일부 수정이 안되어있는 부분은 구현이 완료되는대로 수정 예정입니다.
