### ISSUE TITLE
[ Refactor ] : 12/16기준 피드백 수정 및 리팩토링 진행

### ISSUE THREAD

**Issue by kkb00714** [kkb00714/ManiToOne#131]
##  설명
코드 피드백 및 버그 수정을 진행하며, 전체적인 리팩토링을 진행합니다.

## TO-DO
- [x] 서비스 내 Status(정지, 탈퇴) 처리에 대한 Exception 설정하기
- [x] 컨트롤러 코드 내의 비즈니스 로직 분리하기
- [x] 환경변수로 정의할 내역 정리하기
- [x] 리팩토링 하기
- [x] 프로필 수정 기능 추가
- [x] 프로필 이미지를 jpg, png가 아니면 제한하기
- [x] OAuth2 도메인 변경 및 적용하기
- [x] OAuth2 name 컬럼 31자로 제한 늘리기 (구글 로그인 시 name 컬럼이 최대 30자이기 때문)
- [x] 로그아웃 버튼 css를 index -> header로 옮기기
- [x] 회원 탈퇴 버튼이 안보임 -> ????? 기능 추가해둔 게 사라졌다..
- [x] 프로필 페이지에서 로그아웃 버튼 안보임
