### ISSUE TITLE
[ FEAT ] : 공통 템플릿 작업

### ISSUE THREAD

**Issue by listoria** [kkb00714/ManiToOne#24]
##  설명
기본 프론트 엔드 화면 템플릿 작업

## TO-DO
- [x] index, notification, manito, userpage, postdetails 등 피그마를 기반으로 화면 템플릿 작업
- [x] thymeleaf 적용할 수 있도록 요소 세분화 및 분리 작업
- [x] 프로젝트 내에서 사용할 이미지 파일 작업
