### ISSUE TITLE
[ Refactor ] : ReplyPost.java 필드 및 컬럼 이름 변경 요청

### ISSUE THREAD

**Issue by sqrt3** [kkb00714/ManiToOne#40]
##  설명
ReplyPost 도메인에 parrentId라는 필드가 오타인것 같습니다.
ERD 및 도메인 클래스에서 parentId로 변경 요청합니다.

## TO-DO
- [x] 도메인 상의 ReplyPost.parrentId → parentId로 변경
- [x] ERDCloud 상의 ReplyPost.parrentId → parentId로 변경
- [x] DB상의 ReplyPost.parrentId → parentId로 변경

## 기타
답글은 @yoonjong-j 님이 담당하고 계시니 변경 후 커밋 부탁드립니다.

**Comment by yoonjong-j** [comment]
수정 완료했습니다
