### ISSUE TITLE
[ FEAT ] : 마이 페이지, 타 유저 페이지 상세구현

### ISSUE THREAD

**Issue by sqrt3** [kkb00714/ManiToOne#58]
##  설명
> 마이 페이지가 아닐때 ( 타 유저 페이지 일때 )
> → 숨긴 게시글 버튼이 보이지 않도록 수정합니다.
> ... 버튼은 마이 페이지일땐 숨기기 버튼이, 타 유저 페이지일땐 신고하기 버튼이 보이도록 수정
> JS와 HTML파일을 분리합니다.

## TO-DO
- [x] 타 유저 페이지에서 숨긴 게시글 버튼이 보이지 않도록 수정
- [x] ... 버튼은 마이 페이지일땐 숨기기 버튼이, 타 유저 페이지일땐 신고하기 버튼이 보이도록 수정
- [x] HTML과 JS 파일 분리하기
