### ISSUE TITLE
[ FEAT ] : 마니또 api와 프론트엔드 연결

### ISSUE THREAD

**Issue by listoria** [kkb00714/ManiToOne#66]
##  설명
마니또 api들과 프론트엔드 연결 작업

## TO-DO
- [x] 각 api들과 프론트엔드 기본 연결
- [x] 필요에 따라 코드 리팩토링
- [x] 기능 추가 혹은 구조 변경 고려

## 기타
기타 사항을 작성해 주세요
