### ISSUE TITLE
[ Refactor ] : 프론트엔드 및 Security Config 수정

### ISSUE THREAD

**Issue by kkb00714** [kkb00714/ManiToOne#86]
##  설명
프론트엔드 페이지에 대한 디테일 작업을 진행합니다.
Security를 통해 유저의 접근을 통제 및 프론트엔드에 적절한 에러 메시지를 표출하도록 수정합니다. 

## TO-DO
- [x] 로딩 발생 시 페이지에 진행상황 표시하기 (이메일 인증, 회원가입, 비밀번호 찾기)
- [x] 로그인 시 이전 페이지 (로그인 페이지, 회원가입 페이지 등)에 접근하지 못하도록 설정하기
- [x] 값을 잘못 입력한 부분에 대한 에러 표시 변경하기
- [x] 회원가입, 로그인, 비밀번호 페이지 등에서 에러 발생 시 알맞은 alert 띄우도록 수정하기

## 기타
실제 배포할 때는 URI 부분 수정해야 함.
