### ISSUE TITLE
[ FEAT ] : 프로필 상세 페이지 추가 작업

### ISSUE THREAD

**Issue by sqrt3** [kkb00714/ManiToOne#89]
##  설명
유저의 프로필 페이지에 필요한 추가 작업입니다.

## TO-DO
- [x] 내 페이지 일땐 프로필 수정 버튼과 숨긴 피드 버튼이 보이도록 수정
- [x] 팔로잉 팔로워 목록을 확인할 수 있는 모달 추가
- [x] 프로필 뷰에 로그인 한 유저의 닉네임을 전달하도록 수정
